### ISSUE TITLE
Remove unneeded checkbox and radio classes on input and wrapper within answers

### ISSUE THREAD

**Issue by PeterEmil** [Shnoulle/LimeSurvey-Shnoulle#10]
Working with vanilla Bootstrap the classes on the input and wrapper elements giving unwanted results. Best is to remove the `checkbox` and `radio` classes on the wrapper and input.

This issue arises in the following views:
answer_td_input.php (arrays: 5point and 10point)
answer_row.php (arrays: increasesamedecrease)
answer.php (arrays: dualscale)
answer_row_noanswer.php (arrays: listradio)
answer_row_other.php (arrays: listradio)
item.php (yesno: radio)

I can change those files and create pull request for them.

For now we had to remove them via JS but I'm no fan of this way of working. See this code:
```
    //* !  Remove .radio and .checkbox on divs, lis and tds within answers */
    // Because BS default styling is interfering
    // This removal is twofold: first we remove the class on the div or tablecell itself
    // Then we remove the class on the nested input
    // This way we have an unstyled clean base to work from
    // As fallback we override it with css so there is less of a style-jump when refreshing the page
    $('div.radio, li.radio, td.radio').each(function(){
        // Remove on the tablecell
        $(this).removeClass('radio');
        // Remove on the input
        $(this).find('input').removeClass('radio');
    });
    $('div.checkbox, li.checkbox, td.checkbox').each(function(){
        // Remove on the tablecell
        $(this).removeClass('checkbox');
        // Remove on the input
        $(this).find('input').removeClass('checkbox');
    });
    // Even better to remove this junk from views via pull request
```

This issue is related to #5

**Comment by Shnoulle** [comment]
Point is to : don't remove it by JS. If you need it, and it's better for all : best is to remove it from HTML.

+1 to remove the 2 .radio and .checkbox. Use only checkbox-item from the wrapper.

We leave BS for the wrapper, but really , sometimes BS is not the best solution.

**Comment by PeterEmil** [comment]
Thanks for your response. Much appreciated! Do you want me to change the files in the views and create pull requests for them?

**Comment by Shnoulle** [comment]
I just update to last master now, if you can do it after ? I have a lot of merging conflict ......

**Comment by Shnoulle** [comment]
Merging done. I don't think i rework on it before tomorrow end of afternoon. Please : remove .radio and .checkbox :).

PS : i mean : remove on wrapper too if it's OK, but see if awesome-checbox is OK without. If not : update awesome-checkbox ?

**Comment by PeterEmil** [comment]
Can I get permissions to commit feature branch to this repo and create pull request?

**Comment by PeterEmil** [comment]
awesome-checkbox has to be updated as well; `.checkbox-item` and `.radio-item` instead of `.checkbox` and `.radio`

**Comment by PeterEmil** [comment]
The gender question got a different DOM-structure which results in less consistent styling.

**Comment by PeterEmil** [comment]
Some styling-changes are required for the default template to display the inputs correct within arrays. What is best practice: to change this in the theme-css (flat_and_modern.css) or template.css?

**Comment by Shnoulle** [comment]
Don't know ..... I think template.css must be empty : used by LimeSurvey manager only .
Then they more easily update to last template version

**Comment by Shnoulle** [comment]
@PeterEmil : I'm 100% OK with the fix. But it broke existing template system. I think to make a first milestone with only "No broke template => don't do any update in core template".

BUT : maybe without fixing the template : we don't have the awesome checkboc BUT a real checkbox viewabel. If yes : we don't BROKE survey, only some decoration. DO you have time to make a quick test on a checkbox list/radio list and an array ?

**Comment by Shnoulle** [comment]
PS : for testing remind of the RWD : array in little screen :)

**Comment by PeterEmil** [comment]
I tested it with our tfr-base template, which uses no awesome-checkbox. User can act on all radios and checkboxes: that's OK.

**Comment by PeterEmil** [comment]
When default template doesn't use awesome-checkbox the user can view & act on radios and checkboxes as well. So it only is decoration issue.

**Comment by PeterEmil** [comment]
Found another bugger still hiding in the code :)

**Comment by Shnoulle** [comment]
https://github.com/Shnoulle/LimeSurvey-Shnoulle/issues/10#issuecomment-244351082 : Greazt !!

**Comment by olleharstedt** [comment]
Nice work!

**Comment by LouisGac** [comment]
Like I commented in the commit, replacing radio by radio-item makes it more difficult to update awesome-bootstrap-checkboxes. 

I don't really understand what improvement does it bring? What are exactly those "unwanted results"?

**Comment by LouisGac** [comment]
about the css files question: feel free to add a new file if you need it (just add it in the xml, it will be loaded, same with js)

**Comment by Shnoulle** [comment]
@LouisGac : 

1. .checkbox on wrapper + on input 
2. .checkbox are really annoying , just add it with a clean bootstrap : see what you have added tahn css for array question type. Must revert always the .checkbox css in own css.
3. .checkbox is not very interseting if label is not at the place where bs official wait it.
4. default template use awesome-boostrap : ok. But any one can want to use any other system
5. the css update fr=om awesome bootstarp is really quick ... jsut update the class name for a better name

**Comment by Shnoulle** [comment]
@LouisGac : can you have a look at the first comment of @PeterEmil  ? I have the same issue but doing it in css (adding a lot of css to break this awfull .checkbox)

https://github.com/Shnoulle/LimeSurvey-Shnoulle/issues/10#issue-173148533

**Comment by LouisGac** [comment]
> checkbox are really annoying
more annoying than having to hack awesome-bootstrap-checkbox at each update? 
what does mean "annoying"? 

> can you have a look at the first comment of @PeterEmil ?
I did, and my question was: What are exactly those "unwanted results"

(btw: I'm not against that change, just try to understand why it's done, cause it implies a third party component hack. )

**Comment by Shnoulle** [comment]
All checkbox in same column on array, not possible to vertical-align checkbox/radio etc .....

**Comment by PeterEmil** [comment]
The unwanted results are excessive padding on those elements; the styles from Bootstrap form a cascading whitespace. In the default template there are stylistic overrides to undo the damage. Without the class `checkbox` or `radio` on the input and its parent(s) there exists no issue on styling. That's the reason Denis and I prefer to remove them. The input `type=checkbox` and `type=radio` are there to function as hooks for styling.

**Comment by LouisGac** [comment]
> All  checkbox in same column on array
> padding on those elements; the styles from Bootstrap form a cascading whitespace.

that's an annoying unwanted result ;-) 

Maybe rather than hacking the awesome-bootstrap-checkbox css, we should just put the "hack" (radio-item definition) in a

**Comment by PeterEmil** [comment]
In Sass it is very easy to do; including some styles. What is wise? To put this in template.css or an extra overrides.css? I was searching for the cleanest solution. Or we have to put it in a bootstrap-overrides.css like Denis does with some other styles. That way we can put the `class=radio` back only on the inputs, NOT the parents.
We have to check what it exactly is what awesome-checkbox needs. Looks like it is in contrast with Bootstraps styles.

**Comment by LouisGac** [comment]
Maybe an overrides.css would be useful for further purpose?
**Feel free**  to choose what you consider as the best solution. 

I've just been ask to have a look to what you and Denis are doing here so I can guarantee that we'll merge your work with master as soon as it's ready. 

Also: Mazi and Tamo offered to help testing, I'd like them to test each one of the commit in this repository. Maybe we could to start a task manager so we can trace which commit has been tested or not?

**Comment by Shnoulle** [comment]
awesome-bootstrap is easy because it was very simple. But, in fact : they use .radio but need another html.

Then i'm not sure awesome team make the good decison here ....

Not so easy .... 

awesome-bootsrap is template system , right ? Or default by core ?

**Comment by LouisGac** [comment]
You understand the difficulty now :tada: 

You can choose to remove it if you want, but then you must add another way to have nice checkbox/radio buttons, and guarantee that it would work fine on any devices/screens/resolutions (Smartphones, retina screens, 4k screens, etc). Knowing that this question is absolutely critical, because it can makes impossible to answer a survey. 

I personally decided to trust the awesome-bootstrap team, because they are working on that very problem since years.

**Comment by Shnoulle** [comment]
Maybe, but then 2 solutions:

1. Use default radio/checkbox in core=> awesome is a template issue
2. Put by default awesome from core  => allow to disable in config.xml

We can do the same for no-more-table too. 

And i never think it's an easy way : i work with LS since some year ...... and improve some part of HTML view, make some corer template, fix some core template etc ....

I remind the time when we add the jquery button in core => All template are broken, and we have mpore included template than today .....

**Comment by LouisGac** [comment]
well I've been asked to limit the number of core templates to 3. 

What ever the solution you choose, the "default" template (the one automatically selected as template when a total newbee install limesurvey and create its first survey) must have nice radio/checkbox input (not the browser ones) .

**Comment by Shnoulle** [comment]
Yes, i think so. default can have sema look than actual default
see http://testing.sondages.pro/answershtml
http://testing.sondages.pro/answershtml/alternate/base/
http://testing.sondages.pro/answershtml/alternate/old/
http://testing.sondages.pro/answershtml/alternate/awesome/

Objective : base and awesome seems clean without a lot of css in template.css , but default still default.

PS : where did you take the no-more-table. There are a lot , but don't find the good one actually. 
PS2 : sometimes we don't need no-more-table (array with 2 columns for example) : but leave it for default

**Comment by LouisGac** [comment]
no-more-table is more a concept than a component.
see:
https://elvery.net/demo/responsive-tables/

I had to make a special integration of it for LimeSurvey. Here the based code I used:
http://bootsnipp.com/snippets/featured/no-more-tables-respsonsive-table

So you can feel very free to do your own version if needed.

**Comment by Shnoulle** [comment]
OK :).

Then i think i add a no-more-table.css in template

But : use the @media width of bootsrap .....
