### ISSUE TITLE
include tfr-base template as test-template?

### ISSUE THREAD

**Issue by PeterEmil** [Shnoulle/LimeSurvey-Shnoulle#13]
When checking the changed views the tfr-base template behaves more consistent than the default template, because there is no extra layering on top of the vanilla bootstrap. I think it is good to include the tfr-base in this repo for testing.

For instance, the listradio-question gives a correct result using the tfr-base template when switching from `div` to `li` structure. And there are no strange styling-issues on the array-questions or gender-question.

It will be a lot less work to update the default template when it is based on tfr-base as well ;)

**Comment by Shnoulle** [comment]
I have a test template too (removge a whole bunch of already included part) : > good idea to include 2 test template more :+1:

**Comment by PeterEmil** [comment]
Shall I temporary remove the .gitignore for /upload/templates so I can commit tfr-base?

**Comment by Shnoulle** [comment]
No : we can use another directory for base template.
Let me do this this afternoon (updating config-default)

**Comment by PeterEmil** [comment]
Cool!

**Comment by Shnoulle** [comment]
Done, PS : for testing purpose, i use directly owntemplates/default for my different template. Then updated only with config.php

**Comment by Shnoulle** [comment]
Done : can be tested : base_awesome and default work actually
