### ISSUE TITLE
Replace td for th in thead on arrays

### ISSUE THREAD

**Issue by PeterEmil** [Shnoulle/LimeSurvey-Shnoulle#14]
On some arrays there is a td instead of a th in the thead. Best is to change that so the structure is in line with other arrays. And we don't get styling-issues down the line ;)

**Comment by Shnoulle** [comment]
Yep,

And <thead><tr class="heading" ... for heading heading-repeat class.

**Comment by Shnoulle** [comment]
Maybe this can be merged in core now ?

**Comment by PeterEmil** [comment]
Yes!

**Comment by tammoterhark** [comment]
Peter: great. I just talked (IRC) with Denis. He will make clear what needs to be done on short term (two/three weeks) and what will be in the next major release in some months.

**Comment by Shnoulle** [comment]
Yes : i try to separate Milestine

2.51 : try to make a puill requets for actual core.
2.52 : hope for middle of september (i jsut have to end ul/li and empty label)
2.53 : after

**Comment by tammoterhark** [comment]
Peter, can you push what you ahev done here?

**Comment by PeterEmil** [comment]
All work done has its own commits :)

**Comment by Shnoulle** [comment]
.... i reset some to td ....

Must be redone on all array

**Comment by Shnoulle** [comment]
Remark : in fact th must be used for header cell and the empty cell at start of all table IS NOT and header cell .

Boostrap is broken : must fix boostrap

**Comment by LouisGac** [comment]
Don't break the Internet!  :stuck_out_tongue:

**Comment by Shnoulle** [comment]
In fact : i don't do it, but if someone make the fix for whoile, i merge it.

@PeterEmil : remind : now : the branch is https://github.com/LimeSurvey/LimeSurvey/tree/answers_html

Don't push here, and don't pull too (i don't tested mastyer merging actually)

**Comment by Shnoulle** [comment]
Seems not needed currently ? Boostrap.css dependant ?
