### ISSUE TITLE
Remove array for some list

### ISSUE THREAD

**Issue by Shnoulle** [Shnoulle/LimeSurvey-Shnoulle#17]
Multiple choice with comment and multiple numeric question type use array for HTML views .
This must be fixed ....

**Comment by Shnoulle** [comment]
Not sure for milestone : because it's very needed , but it can be done after (and i want to go more quicly)

**Comment by PeterEmil** [comment]
You mean we use ul / li instead?

**Comment by Shnoulle** [comment]
Think 2.06 system is better: 
````
<ul class="question-list">
<li id="javatdXXXX"><tag class="checkbox-item"><input checkbox><label (or not, don't remind)></tag><tag class="text-item"><label or not><input text></tag></li>
````

After we can replace the ul li vy div and choose what we want for tag. 
If needed
````
ul.question-list{display:table}
ul.question-list li{display:table-row}
ul.question-list li > tag {display:table-cell}
````

Maybe the ul.question-list need a specific class when there are more than 1 item inside.

**Comment by Shnoulle** [comment]
I'm unsure for the MileStone : if time is OK, i hope 2.52 (then LS3 )
