### ISSUE TITLE
Latest version of Peter's work for TFR

### ISSUE THREAD

**Issue by tammoterhark** [Shnoulle/LimeSurvey-Shnoulle#18]
Denis, here is the work that Peter did until so far. Since he did not touch the question views, some of the work is unnecessary, but it give a direction.

[tfr-base_160906.zip](https://github.com/Shnoulle/LimeSurvey-Shnoulle/files/456932/tfr-base_160906.zip)

**Comment by tammoterhark** [comment]
[TFR.zip](https://github.com/Shnoulle/LimeSurvey-Shnoulle/files/456940/TFR.zip)

And here is another one, I made it yesterday.

**Comment by Shnoulle** [comment]
Why Peter can pull it in directly ? https://github.com/Shnoulle/LimeSurvey-Shnoulle/tree/answers_html/templates-test

He ask me management on this repo and a way to test some personal template .

I made it like it actually ....

**Comment by tammoterhark** [comment]
Denis: can you assign Peter?
Peter, can you place these in uploads/templates? I cannot do that...

**Comment by PeterEmil** [comment]
I certainly can pull it in myself, I just didn't know that @tammoterhark uploaded this. He asked for a zip file, I thought he would use it for the IRC...

**Comment by tammoterhark** [comment]
Sorry, my fault...

**Comment by tammoterhark** [comment]
I wanted to make it available for the people that were present at that meeting. I thought that it was easier to do that this way and then post the URL of this issue in the IRC. But actually adding this to the repo will make it testable...

**Comment by PeterEmil** [comment]
Done.

**Comment by Shnoulle** [comment]
Hard to fix HTML + make a good template at same time ;).

See https://github.com/Shnoulle/LimeSurvey-Shnoulle/issues/19 . I move TFR to templates just after.
