### ISSUE TITLE
different structure array listradio - list radio with comments

### ISSUE THREAD

**Issue by tammoterhark** [Shnoulle/LimeSurvey-Shnoulle#20]
Using: docs\demosurveys\ls205_sample_survey_multilingual.lss

![fireshot screen capture 018 - sample limesurvey en_fr_de _ single choice question - sclone_toolsforresearch_com_index_php_282267](https://cloud.githubusercontent.com/assets/6483317/18352002/ce01aaf0-75dc-11e6-8769-4f4eefd8d58c.png)

**Comment by tammoterhark** [comment]
The first one uses "li", the second one "div"

**Comment by tammoterhark** [comment]
\application\views\survey\questions\listradio\rows\answer_row.php

and

**Comment by tammoterhark** [comment]
\application\views\survey\questions\listradio\rows\answer_row.php

and

\application\views\survey\questions\list_with_comment\list\rows\answer_row.php

have completely different structure. I leave this to the professionals...

**Comment by PeterEmil** [comment]
Changed the title to reflect the issue more clearly; this is template-independent.

**Comment by tammoterhark** [comment]
You are right, this is a views thing!

**Comment by tammoterhark** [comment]
Testing on this one:
http://sclone.toolsforresearch.com/index.php/282267?lang=en

sclone= Shoulle's CLONE

template is tfr-base2 in /upload/templates because tfr-base in template dir has error (not using the right pstpl files, perhaps because it has a "-" in the file name, which does not work in the /templates directory, but does work in/upload/templates because we ran into this about a year ago)

**Comment by Shnoulle** [comment]
Yes, i update list , but not list with comment actually. aligment is same after done everywhere.

Linked to https://github.com/Shnoulle/LimeSurvey-Shnoulle/issues/3

**Comment by Shnoulle** [comment]
Done : https://github.com/Shnoulle/LimeSurvey-Shnoulle/commit/8dc0e65845ef2e7c49851004717b06b5b975c33f
