### ISSUE TITLE
Sometime labels are bold, other times normal

### ISSUE THREAD

**Issue by tammoterhark** [Shnoulle/LimeSurvey-Shnoulle#21]
![fireshot screen capture 019 - sample limesurvey en_fr_de _ single choice question - sclone_toolsforresearch_com_index_php_282267_lang en](https://cloud.githubusercontent.com/assets/6483317/18352620/6722b100-75df-11e6-8c3e-b5e1c6800ceb.png)

**Comment by Shnoulle** [comment]
label default from bootstrap are bold. And i move actually answer text to label. Better.

But not done everywhere.

Template must see if he want bold lable or not.

**Comment by tammoterhark** [comment]
Denis, should it not be equal in the base template? Without overriding Bootstrap? Isn't this a part of making all views more consistent?

**Comment by Shnoulle** [comment]
After fixing HTML : all label are inside label. Then without template.css : **all** label are shown in bold : Boostrap css.

**Comment by tammoterhark** [comment]
OK, that is great! Sorry that I sometimes do not understand you instantly. Not used to short messages in technolingo...
