### ISSUE TITLE
Different line spacing between two multiple choice question types

### ISSUE THREAD

**Issue by tammoterhark** [Shnoulle/LimeSurvey-Shnoulle#22]
![fireshot screen capture 020 - sample limesurvey en_fr_de _ multi choice question - sclone_toolsforresearch_com_index_php_282267](https://cloud.githubusercontent.com/assets/6483317/18354823/4e3a79f4-75e7-11e6-9e79-5144febb8305.png)

**Comment by tammoterhark** [comment]
First one: div structure, second one: table structure.

**Comment by Shnoulle** [comment]
And the 2 must be ul/li

You have same for multiple text and multiple numeric  : in https://github.com/Shnoulle/LimeSurvey-Shnoulle/issues/3

The HTML must be something like this
````
<ul class="list-unstyled radio-list answers-list col-sm-{$colWidth} col-xs-12">
  <li id="javatbd{name}" class="row form-group answer-item radio-item">
    <input value="A1" name="{name}" id="answer22549X14X68A1" type="radio">
    <label for="answer{name}" class="control-label radio-label">
        Un exemple d'option de réponse    </label>
  </li>
</ul>  
````

The colWidth is by default at 12, but question attribute can update it
replace radio-list / radio-item by {element_type}-item
Inside the li : we can have multiple part.

Exemple for multiploe text:
````
<label class="col-sm-6">The label</label>
<div class="col-sm-6"><input></div>
````

Already in https://github.com/Shnoulle/LimeSurvey-Shnoulle/issues/3

**Comment by Shnoulle** [comment]
See https://github.com/Shnoulle/LimeSurvey-Shnoulle/commit/8c6d2e4d800be3ce77f01c82aaa0a962c98b44b9
