### ISSUE TITLE
Default template: cleanup of .css and .pstpl files (1st phase)

### ISSUE THREAD

**Issue by tammoterhark** [Shnoulle/LimeSurvey-Shnoulle#25]
template.css is a mess at the moment. Cleanup and categorize

**Comment by Shnoulle** [comment]
Remove extra div (welcome and question have a bunch), remove still existing table (completed.pstpl).

**Comment by LouisGac** [comment]
well if Peter want to use SASS, it doesn't matter what template.css looks like.
The important thing will be that the scss file be cleaned and organized.

**Comment by tammoterhark** [comment]
I know, but we are not there yet. For now we need to have a working default template and I want Peter to work on the things that I cannot do. I need this to be organised better, else I cannot find my way. Currently it is a bit messy...

**Comment by LouisGac** [comment]
CSS is extremely messy and unreadable by nature. To know what rule applies, you have a mix between the the selector specificity (see:https://www.w3.org/TR/css3-selectors/#specificity ) and the position in the document it self. CSS file is made to be read by the navigator, not by human.

So, there is so many debates, so many different ways to "try" to organize it. BEM is a very good one: http://getbem.com/introduction/. Other companies like Facebook decided to totally abandoned CSS classes for JavaScript object (see: https://speakerdeck.com/vjeux/react-css-in-js)

Whatever the solution you use (probably a home made solution), it's a very hard job. IMHO: If you know that Peter will reorganize the css with Sass, you'd rather not lose too much time reorganizing the current css. 

How not to get lost? Don't read the file itself, but rather use the code explorer of your browser (the good old way).

**Comment by tammoterhark** [comment]
OK, I'm convinced. I will only change what is necessary. No cleanup. That can be done later when we use inheritance, with SASS

**Comment by Shnoulle** [comment]
Think , for user : we need cleaner separation of files.

**Comment by tammoterhark** [comment]
Like:
bootstrap.min.css (unchanged from getbootstrap.com)
limesurvey.css (for limesurvey functional specifics)
template.css (for styling)

Is that what you mean? If so, we agree...

**Comment by Shnoulle** [comment]
Yes : something like that.

Maybe some functionnality moved to : 
- no-more-table
- awesome-checkbox

**Comment by tammoterhark** [comment]
OK by me. But for now: change as little as possible in order to avoid lots of rework. 

When inheritance works: all .css files are in "base" template and only styling is in child template. 

Plus overrides that need to be there because template buiolder want to do functionally something different from base template.

**Comment by tammoterhark** [comment]
Pull request https://github.com/Shnoulle/LimeSurvey-Shnoulle/pull/26
