### ISSUE TITLE
About css for mandatory error (by line) and some other

### ISSUE THREAD

**Issue by Shnoulle** [Shnoulle/LimeSurvey-Shnoulle#27]
Boostrap have for form-group a dedicated class for error : has-error : http://getbootstrap.com/css/#forms-control-validation

I start to use it in https://github.com/Shnoulle/LimeSurvey-Shnoulle/commit/c17fe4698e7e3f398491de0d398a7e7e2eea7208#diff-6c59498c409fc45554c2c3b2bc027874R23 : the line is form-group and have has-error if alert is set.

But before for array : i use 
tr : bg-danger class 
th : text-danger

I think it must use always form-group + has-error : seems OK ? + errormandatory on the th (answertext)

PS : actual solution use no class on tr, no class on th : only a label class="error" : seems really dirty

**Comment by Shnoulle** [comment]
This fix https://bugs.limesurvey.org/view.php?id=11645

**Comment by LouisGac** [comment]
Seems cleaner to me.  at the same time, you could have a look to the Expression Manager which add class "good" or "error" in certain conditions. 
eg: https://github.com/LimeSurvey/LimeSurvey/blob/master/application/helpers/expressions/em_manager_helper.php#L7339

**Comment by Shnoulle** [comment]
Yes : 2nd part or third. But this one is already in https://github.com/LimeSurvey/LimeSurvey/pull/258 project (close and deleted due to EM rewriting). 

After relevanceOn/relevanceOff jquery event, i thinking adding setError/setSuccess event .

The setSuccess can be really great : we can count the number of error : if ===0 => remove the input-error class adedd.

**Comment by LouisGac** [comment]
yep, that would be great.

**Comment by PeterEmil** [comment]
Just ringing in to + @Shnoulle : `has-error` is certainly better than `danger` or `error` because it doesn't get in the way Bootstrap uses its error-styling. We can hook the styling to our error-handling if we like, or can choose another styling. Perfect. In unison with the removal of error-messages from core when there is no need for it this will rock ;)

**Comment by Shnoulle** [comment]
I update array and some list to use has-error with form-group + control-label + form-control.

But in fact : for starting : it's more for "errormandatory" replacement. The actual label label-error in 2.51.

After : yes : for Expression Manager javascript system too.

**Comment by maziminke** [comment]
Just a comment/question: What do you think about adding a class like "has-error" at different levels like BODY (to indicate that there is an error at that page), the "question" DIV (to indicate a certain question has an error) and - maybe depending on the question type - also at the related TR/LI element to indicate to which item an error refers to (if possible).

**Comment by Shnoulle** [comment]
Not has-error : because it's done just for the form-group : then thye lable + input where there are this error.

For the question part (wrapper) : we already have input-error if a mandatory question wasn't anserwed.

For example with a multiple short text : we must have finally , if user answered only to the first line

````
<div id="questionID" class="input-error">
The question text
<ul class="answers-list subquestions-list text-list">
<li class="text-item form-control"><label for="answerSGQ" class="control-label">label</label><input type="text" class="form-control" value=""></li>
<li class="text-item form-control has-error "><label for="answerSGQ" class="control-label">label</label><input type="text" class="form-control" value=""></li>
</ul>
````

For body part : in fact : for accessibility : the title of the p&age must contain an information about "There are an error in the page" : i already put a dev/feature request to allow template to show : 

- A page have error (after submit)
- Show the list of error in the page with the link to the question id.

Actually , even with plugin : i dodn't find a way to get some information from the ExpressionManager API ...

Denis
PS : remind than actually : only "mandatory" system is tested here. EM need improvment for other system, but it's in future.
