### ISSUE TITLE
Proposal refactor icon system in views

### ISSUE THREAD

**Issue by PeterEmil** [Shnoulle/LimeSurvey-Shnoulle#29]
As mentioned in https://github.com/Shnoulle/LimeSurvey-Shnoulle/pull/28#issuecomment-246619316 I'll propose a refactoring to the views to easily create and change icons.

The HTML will be as follows:

```
<div class="label label-danger ls-icon">
    <?php echo $ansrow['answertext']; ?>
</div>
```

We like to do it this way because now **every** element can have an icon prepended to it. This is a more flexible approach. Both Bootstrap and Font-Awesome prefer to create a separate element for this purpose, so I will test if our proposal won't affect the flow of the DOM or create stylistic havoc.

The `ls-icon` declaration copies the rules from the used icon-font, like `fa` does. Bootstrap uses glyphicons and this is declared in its css as well, so it is easy to switch between these two systems. Not sure if we need a separate css-file for it; it can be prepended to `template.css` as well, with a solid documentation so any user can change it easy - within reason. When using Sass or any other preprocessor it's just a matter of extending the to be used icon-class (`fa` or `glyphicon`, etc).

The icon will be rendered as a `:before`. Then the glyph of the icon is written on the element getting this icon. So in the example above the css will simply look like this:

```
.label-danger:before{
    /* exclamation-circle */
    content: f06a;
}
```

We will comment the glyph before declaring the unicode so the complete declaration is self-explanatory.

**Comment by PeterEmil** [comment]
I'll create a separate branch so it can be checked before eventual merging.

**Comment by Shnoulle** [comment]
OK, then no icon for Gender : only CSS.

I know it's more clean : but in fact offer icon give me an idea about Yes/no : "Question attribute" : Choose the icon.

I know my client can really appreciate this : have :+1: :-1:  OR :exclamation: OR any idea ....

**Comment by Shnoulle** [comment]
PS : the hardes seems to be actual date : using Bootsrap date from YiiWheels make it harder to have a clean own system (i already try using selector etc ...)

**Comment by Shnoulle** [comment]
TODO : move to LimeSurvey core, my work is done exceptb the mlast boostrap-package system. After it's just some improvement (think template-default : only some package)

**Comment by Shnoulle** [comment]
PS: date totally use FontAwesome now , by default.
