### ISSUE TITLE
alignment in table : bootsrtrap style or not ?

### ISSUE THREAD

**Issue by Shnoulle** [Shnoulle/LimeSurvey-Shnoulle#30]
The .table bootsrap style have some issue

1. Set the padding (awesome-checkbox} : ok force it again
2. Set the alignment : clearly we need better alignement than vertical-align: top; ...

Question : did we use boostrap class for alignemùent or did we fix it only by template ? 

In template-core.css : added 
````
/* Basic alignment */
.table.question td
{text-align:center;vertical-align:middle}
.table.question tbody th
{text-align:right;vertical-align:middle}
.table.question thead th
{text-align:center;vertical-align:bottom}
.table.question .answertext{text-align:right}
.table.question .answertextright{text-align:left}
````

Another remark : maybe we can remove completely usage of table class, adding a table-question + (table-radio|table-checkbox|table-text|table-dropdown) to use an table adapted class.

I push tomorrow some array adaptation more with a big fix for awesome-checkbox + awesome-checkbox in table

**Comment by LouisGac** [comment]
Question is: why do you need to remove this class?

**Comment by Shnoulle** [comment]
Some default css from bootstrap (aligmen,t for example) must be rewritten after. Thinking too for the border in no-more-table system (i use table, not tables : then template.css don't take it).

PS : i'm unsure too for the sr-only in label, adding a ls-sr-only it's maybe more easy ..... (just position absolute and clipping to 0 : http://webaim.org/techniques/css/invisiblecontent/

**Comment by Shnoulle** [comment]
And actually the question is to use text-center/text-right class. 

But the user must do

`table.question .text-center {text-align:left}`

And i don't lik ethis way ....

**Comment by Shnoulle** [comment]
Move to template-core + template
