### ISSUE TITLE
No string for mandatory question

### ISSUE THREAD

**Issue by Shnoulle** [Shnoulle/LimeSurvey-Shnoulle#4]
It's needed for accessibilty, and can be great for javascript (show tooltip, deactivate submit if a mlandatory exist and show something with text).

See https://github.com/SondagesPro/LS-moreAccessibility/blob/master/moreAccessibility.php#L272 to be added in a plugin activated by default or in DBplugin (because it can not be deactivated and are already activated).

See https://bugs.limesurvey.org/view.php?id=11500

**Comment by Shnoulle** [comment]
Plugin can do it : i do a core pugin for this not 3.0 core issue (can be done after)

**Comment by LouisGac** [comment]
why a plugin? I'd say this should be core.

**Comment by Shnoulle** [comment]
Core plugin activated by default, it's more easy to do a core plugin actually.

https://github.com/LimeSurvey/LimeSurvey/blob/master/application/helpers/SurveyRuntimeHelper.php#L1618 

````
$event->set('mandatory',$event->set('mandatory')."<div class='sr-only'>".gT("This question is mandatory.")."</div>";
````

And more easily updatable by another dev : less option, less files, less code
