### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by tammoterhark** [Shnoulle/LimeSurvey-Shnoulle#9]
What do we do with Mazi's (and probably other people's) wish to have backward compatibility?

Personally I would not bother too much and declare that the template that we make is for new releases of LimeSurvey. Otherwise too much work will have to be done for old installations.

**Comment by Shnoulle** [comment]
I really think we can not have a complete backward compatibilty. BUT: readding ul/li imrove compatibility.

Some other are hard to find a good way to improve compat: numeric slider is the best example. It's a lot of question is compatible and we just have to fix some css/js (less than 100/200 line for example), i think it's OK. 

Another example : i really think we need to have this https://github.com/Shnoulle/LimeSurvey-Shnoulle/issues/7 class sytem (i'm unsure for text-danger, may just replace by errormandatory (2.06 have td span class='errormandatory' : then if only text are colored it's OK BUT if we have td .errormandatory in css : it's semi broken (little broke : one css line to update)

**Comment by Shnoulle** [comment]
Mpve to 3.0 : no backward compatibility.
